### ISSUE TITLE
Update bindings

### ISSUE THREAD

**Issue by Satont** [dnsge/twitch-eventsub-bindings#2]
Can you please update bindings?

If you have no time, but open to pr - i can do that.

**Comment by dnsge** [comment]
Hey @Satont :)

I can take a look into updating the bindings. I created this script to run in the browser to generate the bindings automatically: https://github.com/dnsge/twitch-eventsub-bindings/blob/a5b92df4a84a683d6012725c41919f03accad70c/generation_script.js but I've kinda forgotten how to use it (and didn't document it -- oops). 

It may be easier to manually update the bindings in the places where changes have been made. Do you know which structs need to be updated/created?

**Comment by Satont** [comment]
Actually a lot of events now missed, so manually add them feels destructive.

**Comment by Satont** [comment]
Added some events needed for me in https://github.com/dnsge/twitch-eventsub-bindings/pull/3

**Comment by dnsge** [comment]
#3 merged in. Cut a new release v1.2.0.
